// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxRFd50QWacs9fluJ2_oOsdFHdP7gjuUk',
    appId: '1:210778838308:web:f0d8fb7943a26b165b4fb1',
    messagingSenderId: '210778838308',
    projectId: 'finalapp-adb21',
    authDomain: 'finalapp-adb21.firebaseapp.com',
    storageBucket: 'finalapp-adb21.firebasestorage.app',
    measurementId: 'G-J53MGKCS06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3p_bPFvzMnpbrDlUbjb5k5n3KngO4cZk',
    appId: '1:210778838308:android:c022653127389b695b4fb1',
    messagingSenderId: '210778838308',
    projectId: 'finalapp-adb21',
    storageBucket: 'finalapp-adb21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSzU5_zUYrUlVyPGEnxP15k_KEuFcQfXc',
    appId: '1:210778838308:ios:fd6b7b80c9d1e6a05b4fb1',
    messagingSenderId: '210778838308',
    projectId: 'finalapp-adb21',
    storageBucket: 'finalapp-adb21.firebasestorage.app',
    iosBundleId: 'com.example.finalflutterexam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSzU5_zUYrUlVyPGEnxP15k_KEuFcQfXc',
    appId: '1:210778838308:ios:fd6b7b80c9d1e6a05b4fb1',
    messagingSenderId: '210778838308',
    projectId: 'finalapp-adb21',
    storageBucket: 'finalapp-adb21.firebasestorage.app',
    iosBundleId: 'com.example.finalflutterexam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxRFd50QWacs9fluJ2_oOsdFHdP7gjuUk',
    appId: '1:210778838308:web:c41ffdc1b5cf80d45b4fb1',
    messagingSenderId: '210778838308',
    projectId: 'finalapp-adb21',
    authDomain: 'finalapp-adb21.firebaseapp.com',
    storageBucket: 'finalapp-adb21.firebasestorage.app',
    measurementId: 'G-WPXNWW3LY1',
  );
}
